In [14]:
import pandas as pd

df = pd.read_csv('results.csv')

def calculate_mape_group(group):
    y_true = group['y_true']
    y_pred = group['y_pred']
    return 100 * (abs((y_true - y_pred) / y_true)).mean()

mape_result = df.groupby(['set_name', 'method_name']).apply(calculate_mape_group).reset_index(name='mape')
mean_time = df.groupby(['set_name', 'method_name'])['time'].mean().reset_index(name='mean_time')
result = pd.merge(mape_result, mean_time, on=['set_name', 'method_name'])

result

/var/folders/wv/6xv2r7px5rzds9j12s1bfkhr0000gn/T/ipykernel_71152/2007795485.py:10: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  mape_result = df.groupby(['set_name', 'method_name']).apply(calculate_mape_group).reset_index(name='mape')

   set_name                   method_name       mape  mean_time
0         A                  Basic Greedy  39.899534   0.000171
1         A             SA__2-opt_2-steps  23.033249   1.247564
2         A    SA__2-opt_2-steps_post2opt  23.033249   1.247564
3         A    SA__2-opt_2-steps_post3opt  23.033249   1.247564
4         A     SA__2-opt_2-steps_postALL  19.321008   1.247564
5         A   SA__2-opt_2-steps_postOropt  23.033249   1.247564
6         A    SA__2-opt_2-steps_postSwap  23.033249   1.247564
7         A             SA__3-opt_2-steps  18.785086   1.361940
8         A    SA__3-opt_2-steps_post2opt  18.785086   1.361940
9         A    SA__3-opt_2-steps_post3opt  18.785086   1.361940
10        A     SA__3-opt_2-steps_postALL  18.693222   1.361940
11        A   SA__3-opt_2-steps_postOropt  18.785086   1.361940
12        A    SA__3-opt_2-steps_postSwap  18.785086   1.361940
13        A            SA__or-opt_2-steps  10.252534   1.250439
14        A   SA__or-opt_2-steps_post2opt  10.252534   1.250439
15        A   SA__or-opt_2-steps_post3opt  10.252534   1.250439
16        A    SA__or-opt_2-steps_postALL  10.928805   1.250439
17        A  SA__or-opt_2-steps_postOropt  10.252534   1.250439
18        A   SA__or-opt_2-steps_postSwap  10.252534   1.250439
19        M                  Basic Greedy  54.217384   0.001473
20        M             SA__2-opt_2-steps  28.264129   2.988919
21        M    SA__2-opt_2-steps_post2opt  28.264129   2.988919
22        M    SA__2-opt_2-steps_post3opt  28.264129   2.988919
23        M     SA__2-opt_2-steps_postALL  12.000881   2.988919
24        M   SA__2-opt_2-steps_postOropt  28.264129   2.988919
25        M    SA__2-opt_2-steps_postSwap  28.264129   2.988919
26        M             SA__3-opt_2-steps  12.707150   5.054621
27        M    SA__3-opt_2-steps_post2opt  12.707150   5.054621
28        M    SA__3-opt_2-steps_post3opt  12.707150   5.054621
29        M     SA__3-opt_2-steps_postALL  12.044788   5.054621
30        M   SA__3-opt_2-steps_postOropt  12.707150   5.054621
31        M    SA__3-opt_2-steps_postSwap  12.707150   5.054621
32        M            SA__or-opt_2-steps  22.397107   2.947525
33        M   SA__or-opt_2-steps_post2opt  22.397107   2.947525
34        M   SA__or-opt_2-steps_post3opt  22.397107   2.947525
35        M    SA__or-opt_2-steps_postALL  12.582291   2.947525
36        M  SA__or-opt_2-steps_postOropt  22.397107   2.947525
37        M   SA__or-opt_2-steps_postSwap  22.397107   2.947525
38        P                  Basic Greedy  34.933801   0.000178
39        P             SA__2-opt_2-steps  16.311171   1.249231
40        P    SA__2-opt_2-steps_post2opt  16.311171   1.249231
41        P    SA__2-opt_2-steps_post3opt  16.311171   1.249231
42        P     SA__2-opt_2-steps_postALL  18.337039   1.249231
43        P   SA__2-opt_2-steps_postOropt  16.311171   1.249231
44        P    SA__2-opt_2-steps_postSwap  16.311171   1.249231
45        P             SA__3-opt_2-steps  19.027592   2.023072
46        P    SA__3-opt_2-steps_post2opt  19.027592   2.023072
47        P    SA__3-opt_2-steps_post3opt  19.027592   2.023072
48        P     SA__3-opt_2-steps_postALL  20.270049   2.023072
49        P   SA__3-opt_2-steps_postOropt  19.027592   2.023072
50        P    SA__3-opt_2-steps_postSwap  19.027592   2.023072
51        P            SA__or-opt_2-steps  13.008549   1.231508
52        P   SA__or-opt_2-steps_post2opt  13.008549   1.231508
53        P   SA__or-opt_2-steps_post3opt  13.008549   1.231508
54        P    SA__or-opt_2-steps_postALL  11.589437   1.231508
55        P  SA__or-opt_2-steps_postOropt  13.008549   1.231508
56        P   SA__or-opt_2-steps_postSwap  13.008549   1.231508

In [12]:
result[result.method_name == "Basic Greedy"]

   set_name   method_name       mape  mean_time
0         A  Basic Greedy  39.899534   0.000166
19        M  Basic Greedy  54.217384   0.001438
38        P  Basic Greedy  34.933801   0.000184